name: triage
description: "Triage App for Psychiatric Units"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The core SQLite engine for Flutter
  sqflite: ^2.3.3+1
  # Provides utility functions for manipulating file system paths
  path: ^1.9.0

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/patients/
    - assets/assessments/
    - assets/medications/
    - assets/questions/
    - assets/sql/
flutter_intl:
  enabled: true
