import 'package:triage/classes/acuity.dart';

import 'date_time_utilities.dart';
import 'medication_services.dart';

enum PatientState { stable, labile, agitated, catatonic, withdrawn }

class Patient {
  final String patientUuid; //'02039325-2425-4bf3-bf85-1ec81a797e25',
  final String firstName; //'Silvain',
  final String lastName; //'Saulter',
  final String phn; //'807-831-0857',
  final int phaseStepId; //301,
  final String email; //'ssaulter0@spotify.com',
  final String ssn; //'305-41-7220',
  final String title; //'Rev',
  final String city; //'Vyerkhnyadzvinsk',
  final String country; //'final String Belarus',
  final String streetAddress; //'0565 Blue Bill Park Avenue',
  final String state; //null,
  final String postalCode; //null,
  final DateTime dob; //'4/27/2019',
  final DateTime admitted; //'12/25/2025',
  final AcuityLevel acuityLevel; //3,
  final int policeReports; //2,
  final int assessments; //279,
  final int medications; //11,
  final MedicationSafetyAudit medicationSafetyAudit; //1,
  final String status; //'Unstable',
  final String path; //'Custody',
  final int flags; //'Involuntary',
  final String phone; //'443-449-5848',
  final String familyDoctorPhone; //'857-582-7784',
  final String contactPhone; //'364-303-6922',
  final String pharmacyPhone; //'433-729-8681',
  final String pharmacyFax; //'509-196-1665',
  final String familyDoctorName; //'Silvain Saulter',
  final String relation; //'Partner',
  final String contactName; //'Silvain Saulter',
  double currentHeight;
  String heightUoM;
  double currentWeight;
  String weightUoM;
  String narrativeHint;

  Patient({
    required this.patientUuid,
    required this.firstName,
    required this.lastName,
    required this.phn,
    required this.phaseStepId,
    required this.email,
    required this.ssn,
    required this.title,
    required this.city,
    required this.country,
    required this.streetAddress,
    required this.state,
    required this.postalCode,
    required this.dob,
    required this.admitted,
    required this.acuityLevel,
    required this.policeReports,
    required this.assessments,
    required this.medications,
    required this.medicationSafetyAudit,
    required this.status,
    required this.path,
    required this.flags,
    required this.phone,
    required this.familyDoctorPhone,
    required this.contactPhone,
    required this.pharmacyPhone,
    required this.pharmacyFax,
    required this.familyDoctorName,
    required this.contactName,
    required this.relation,
    this.currentHeight = 0,
    this.heightUoM = "cm",
    this.currentWeight = 0,
    this.weightUoM = "kg",
    this.narrativeHint = "",
  });

  factory Patient.fromJson(Map<String, dynamic> item) {
    return Patient(
      patientUuid: item['patient_uuid'],
      //'02039325-2425-4bf3-bf85-1ec81a797e25',
      firstName: item['first_name'],
      //'Silvain',
      lastName: item['last_name'],
      //'Saulter',
      phn: item['phn'],
      //'807-831-0857',
      phaseStepId: item['phase_step_id'],
      //301,
      email: item['email'],
      //'ssaulter0@spotify.com',
      ssn: item['ssn'],
      //'305-41-7220',
      title: item['title'],
      //'Rev',
      city: item['city'],
      //'Vyerkhnyadzvinsk',
      country: item['country'],
      //'Belarus',
      streetAddress: item['street_address'],
      //'0565 Blue Bill Park Avenue',
      state: item['state'] ?? "",
      //null,
      postalCode: item['postal_code'] ?? "",
      //null,
      dob: DTUtilities.sqliteToDart(item['dob']),
      //'4/27/2019',
      admitted: DTUtilities.sqliteToDart(item['admitted']),
      //'12/25/2025',
      acuityLevel: AcuityLevel.values[item['acuity']],
      //3,
      policeReports: item['police_reports'],
      //2,
      assessments: item['assessments'],
      //279,
      medications: item['medications'] ?? 0,
      //11,
      medicationSafetyAudit: MedicationSafetyAudit.values[item['medicationsafety_audit']],
      //1,
      status: item['status'] ?? "",
      //'Unstable',
      path: item['path'],
      //'Custody',
      flags: item['flags'] ?? 0,
      //'Involuntary',
      phone: item['phone'],
      //'443-449-5848',
      familyDoctorPhone: item['family_doctor_phone'],
      //'857-582-7784',
      contactPhone: item['contact_phone'],
      //'364-303-6922',
      pharmacyPhone: item['pharmacy_phone'],
      //'433-729-8681',
      pharmacyFax: item['pharmacy_fax'],
      //'509-196-1665',
      familyDoctorName: item['family_doctor_name'],
      //'Silvain Saulter',
      contactName: item['contact_name'],
      //'Silvain Saulter',
      relation: item['relation'],
      currentHeight:item['current_height'] ?? 0,
      currentWeight:item['current_weight'] ?? 0,
      //'Partner',
      narrativeHint:
          item['narrative_hint'] ?? "", //'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
    );
  }
}
